dir_output : data/hybridization_probability/datasets_test # path to the folder where the dataset will be stored
oligo_length_min: 15  # minimum length of the oligos
oligo_length_max: 25  # maximum length of the oligos
splits_size: [0.3333, 0.3333, 0.3333]  # train , validation and test splits
file_genes: data/hybridization_probability/regions/custom_12.csv  # path to the file containing the desired genes
dataset_size: 20000 # total number of entries of the dataset
oligos_per_region: 350 # maximum number of oligo per region for which the off targets are searched -> assume 5 off-targets per oligo and calculate according to this
n_jobs: 8  # number of available CPUs (if None the maximum number of CPUs will be used)
seed: 547389
nupack_cache: 8.0

######### only for custom source ##########
source: custom # required: indicate that own annotation should be used
source_params:
    file_annotation: data/hybridization_probability/output_genomic_region_generator_ncbi_for_hpc/annotation/GCF_000001405.40_GRCh38.p14_genomic.gtf # data/hybridization_probability/output_genomic_region_generator_ncbi/annotation/GCF_000001405.40_GRCh38.p14_genomic.gtf # required: GTF file with gene annotation
    file_sequence: data/hybridization_probability/output_genomic_region_generator_ncbi_for_hpc/annotation/GCF_000001405.40_GRCh38.p14_genomic.fna # data/hybridization_probability/output_genomic_region_generator_ncbi/annotation/GCF_000001405.40_GRCh38.p14_genomic.fna # required: FASTA file with genome sequence
    files_source: NCBI # optional: original source of the genomic files
    species: Homo_sapiens # optional: species of provid ed annotation, leave empty if unknown
    taxon: vertebrate_mammalian # optional: taxon of the species we are intereste, only for source: ncbi
    annotation_release: GCF_000001405.40-RS_2025_08 # optional: release number of provided annotation, leave empty if unknown
    genome_assembly: # optional: genome assembly of provided annotation, leave empty if unknown
precalculated_annotation_path: output_odt_real_1758010914.122287/annotation
precalculated_annotation_file: annotation_source-NCBI_species-Homo_sapiens_annotation_release-GCF_000001405.40-RS_2025_08_genome_assemly-unknown.fna
genomic_regions:
  gene: true
  exon: false
  exon_exon_junction: false
  cds: false
  intron: false
  intergenic: true

######### alignment method ##########
alignment_method: bowtie
search_parameters:
  -v: 3 # allow up to 3 missmatches
  -k: 10 # just include 10 alignments
hit_parameters:
index_path: /Users/jonas.hagenberg/Documents/Projects/oligo_designer/forks/oligo-designer-toolsuite-AI-filters/data/hybridization_probability/bowtie_filter_hpc/bowtie_filter/db_reference_bowtie_filter.fna